### ISSUE TITLE
npm run build fails to minify

### ISSUE THREAD

**Issue by resson-ntranquilla** [sindresorhus/rgb-hex#6]
[https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify](url)

> Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.

**Comment by resson-ntranquilla** [comment]
That you for the quick response. Please document this clearly in your README so that developers don't waste both their time and yours.
